#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/employees
#    username: root
#    password: codeup
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8888

spring:
  application:
    name: employee-crud-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
  instance:
    hostname: localhost