server.port: ${PORT:8888}

eureka:
  instance:
    name: ${spring.application.name}
    hostname: ${DOMAIN_NAME:localhost}
    non-secure-port: 80
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8661}/eureka/

# TO run this set SPRING_PROFILES_ACTIVE to cloud in Run Configuration
#---
#spring.profiles: cloud

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-45-73-150.compute-1.amazonaws.com:5432/d5fjbjtajgrq0h
    username: borilblpkyvirp
    password: 4aa463c494f9fd6bc2b7a688772fa913d03fd4ce0184a17be91c9de1499fc574

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

#---
#
#spring.profiles: local, default
## this should go in the LOCAL profile
## Should access at: http://localhost:8888/h2/
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

